4k: udev
	./setup.py --4k

warning:
	@echo "+-----------------------------------------------------+"
	@echo "| Please run autorandr.sh to run autorandr manually.  |"
	@echo "+-----------------------------------------------------+"
